server:
  port: 8085

spring:
  application:
    name: notification-service

  messages:
    basename: i18n/error/messages

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  mail:
    host: smtp.gmail.com
    port: 587
    email: edilqedirov023@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/