server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: admin
    password: ${DB_PASSWORD:admin123}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      enable.idempotence: true
      acks: all

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  messages:
    basename: i18n/error/messages

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET:MySuperSecretFallbackKeyForLocalDemo123456789!}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
internal:
  traffic:
    secret: ${INTERNAL_TRAFFIC_SECRET:demo-secure-key-2026}